import {useMemo,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {http,errorMessage} from '../api/http';
import toast from 'react-hot-toast';
import {Modal} from '../components/Modal';
import {StatusBadge} from '../components/StatusBadge';
import {Plus,Eye,Pencil,Trash2,Play,CheckCircle2,UserX,CalendarClock} from 'lucide-react';
import {useAuth} from '../auth/AuthContext';
import {localToday} from '../utils/date';

const today=localToday;
const empty={cliente_id:'',empleado_id:'',fecha:today(),hora_inicio:'09:00',servicio_ids:[] as string[],notas:''};
export function AgendaPage(){
 const{user}=useAuth(); const role=user?.rol||''; const admin=role==='ADMINISTRADOR'; const reception=role==='RECEPCIONISTA'; const stylist=role==='ESTILISTA';
 const[date,setDate]=useState(today()); const[open,setOpen]=useState(false); const[detail,setDetail]=useState<any>(null); const[editing,setEditing]=useState<any>(null); const[form,setForm]=useState<any>(empty); const qc=useQueryClient();
 const{data,isLoading}=useQuery({queryKey:['appointments',date,role],queryFn:async()=>{const r=await http.get('/appointments',{params:{fecha_desde:date,fecha_hasta:date,pagina:1,tamano_pagina:100}});return r.data}});
 const{data:summary}=useQuery({queryKey:['appointment-summary',date,role],queryFn:async()=>{const r=await http.get('/appointments/summary',{params:{fecha:date}});return r.data.data}});
 const{data:clients}=useQuery({queryKey:['appointment-clients'],enabled:!stylist,queryFn:async()=>{const r=await http.get('/clients',{params:{estado:'ACTIVO',pagina:1,tamano_pagina:100}});return r.data.items}});
 const{data:employees}=useQuery({queryKey:['appointment-employees'],enabled:!stylist,queryFn:async()=>{const r=await http.get('/employees',{params:{estado:'ACTIVO',pagina:1,tamano_pagina:100}});return r.data.items}});
 const{data:services}=useQuery({queryKey:['appointment-services'],queryFn:async()=>{const r=await http.get('/services',{params:{estado:'ACTIVO',pagina:1,tamano_pagina:100}});return r.data.items}});
 const refresh=()=>{qc.invalidateQueries({queryKey:['appointments']});qc.invalidateQueries({queryKey:['appointment-summary']})};
 const save=useMutation({mutationFn:()=>editing?http.put(`/appointments/${editing.id}`,form):http.post('/appointments',form),onSuccess:()=>{toast.success(editing?'Cita actualizada':'Cita creada');setOpen(false);setEditing(null);setForm(empty);refresh()},onError:e=>toast.error(errorMessage(e))});
 const status=useMutation({mutationFn:({id,estado,motivo_cancelacion}:{id:string;estado:string;motivo_cancelacion?:string})=>http.patch(`/appointments/${id}/status`,{estado,motivo_cancelacion}),onSuccess:()=>{toast.success('Estado actualizado');refresh()},onError:e=>toast.error(errorMessage(e))});
 const remove=useMutation({mutationFn:(id:string)=>http.delete(`/appointments/${id}`),onSuccess:()=>{toast.success('Cita eliminada');refresh()},onError:e=>toast.error(errorMessage(e))});
 const items=useMemo(()=>[...(data?.items||[])].sort((a:any,b:any)=>String(a.hora_inicio).localeCompare(String(b.hora_inicio))),[data]);
 const edit=(x:any)=>{setEditing(x);setForm({cliente_id:x.cliente_id,empleado_id:x.empleado_id,fecha:x.fecha,hora_inicio:String(x.hora_inicio).slice(0,5),servicio_ids:x.servicios.map((s:any)=>s.servicio_id),notas:x.notas||''});setOpen(true)};
 const toggleService=(id:string)=>setForm((f:any)=>({...f,servicio_ids:f.servicio_ids.includes(id)?f.servicio_ids.filter((x:string)=>x!==id):[...f.servicio_ids,id]}));
 return <div className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="page-title">{stylist?'Mi agenda':'Agenda del día'}</h1><p className="text-slate-500">{stylist?'Solo tus citas y acciones de atención.':'Mostrando únicamente las citas de la fecha seleccionada abajo — cambia la fecha para ver otro día.'}</p></div>{(admin||reception)&&<button className="btn-primary" onClick={()=>{setEditing(null);setForm({...empty,fecha:date});setOpen(true)}}><Plus size={18}/>Nueva cita</button>}</div>
  <p className="-mt-2 text-xs font-semibold uppercase tracking-wide text-violet-600">Vista por día · próximamente semana/mes</p>
  <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[['Total',summary?.total_citas],['Pendientes',summary?.pendientes],['Confirmadas',summary?.confirmadas],['En proceso',summary?.en_proceso],['Finalizadas',summary?.finalizadas],['Canceladas',summary?.canceladas]].map(([l,v])=><div className="card" key={String(l)}><p className="text-xs text-slate-500">{l}</p><p className="text-2xl font-bold">{v??0}</p></div>)}</div>
  <div className="card flex items-end gap-3"><label><span className="label">Fecha</span><input className="field" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div className="ml-auto text-sm text-slate-500">{items.length} citas</div></div>
  <div className="grid gap-3">{isLoading?<div className="card">Cargando agenda...</div>:items.length===0?<div className="card text-center text-slate-500">No hay citas para esta fecha.</div>:items.map((x:any)=><div className="card" key={x.id}><div className="flex flex-wrap items-center gap-4"><div className="min-w-20 text-xl font-bold text-violet-600">{String(x.hora_inicio).slice(0,5)}</div><div className="min-w-56 flex-1"><p className="font-semibold">{x.cliente_nombre}</p><p className="text-sm text-slate-500">{x.empleado_nombre} · {x.servicios.map((s:any)=>s.nombre).join(', ')}</p></div><div className="font-semibold">S/ {Number(x.precio_total||0).toFixed(2)}</div><StatusBadge value={x.estado}/></div><div className="mt-3 flex flex-wrap gap-2 border-t pt-3"><button className="btn-secondary !px-3 !py-2" onClick={()=>setDetail(x)}><Eye size={16}/>Detalle</button>{(admin||reception)&&['PENDIENTE','CONFIRMADA'].includes(x.estado)&&<button className="btn-secondary !px-3 !py-2" onClick={()=>edit(x)}><Pencil size={16}/>Editar</button>}{(admin||reception)&&x.estado==='PENDIENTE'&&<button className="btn-secondary !px-3 !py-2" onClick={()=>status.mutate({id:x.id,estado:'CONFIRMADA'})}><CheckCircle2 size={16}/>Confirmar</button>}{stylist&&x.estado==='CONFIRMADA'&&<button className="btn-primary !px-3 !py-2" onClick={()=>status.mutate({id:x.id,estado:'EN_PROCESO'})}><Play size={16}/>Iniciar</button>}{stylist&&x.estado==='EN_PROCESO'&&<button className="btn-primary !px-3 !py-2" onClick={()=>status.mutate({id:x.id,estado:'FINALIZADA'})}><CheckCircle2 size={16}/>Finalizar</button>}{(stylist||reception||admin)&&['PENDIENTE','CONFIRMADA'].includes(x.estado)&&<button className="btn-secondary !px-3 !py-2" onClick={()=>status.mutate({id:x.id,estado:'NO_ASISTIO'})}><UserX size={16}/>No asistió</button>}{(admin||reception)&&['PENDIENTE','CONFIRMADA','EN_PROCESO'].includes(x.estado)&&<button className="btn-secondary !px-3 !py-2 text-rose-600" onClick={()=>{const m=prompt('Motivo de cancelación');if(m)status.mutate({id:x.id,estado:'CANCELADA',motivo_cancelacion:m})}}>Cancelar</button>}{admin&&x.estado!=='EN_PROCESO'&&<button className="btn-secondary !px-3 !py-2 text-rose-600" onClick={()=>confirm('¿Eliminar permanentemente esta cita?')&&remove.mutate(x.id)}><Trash2 size={16}/>Eliminar</button>}</div></div>)}</div>
  <Modal open={open} title={editing?'Editar cita':'Nueva cita'} onClose={()=>setOpen(false)}><form className="grid gap-4" onSubmit={e=>{e.preventDefault();save.mutate()}}><label><span className="label">Cliente</span><select className="field" value={form.cliente_id} onChange={e=>setForm({...form,cliente_id:e.target.value})} required><option value="">Seleccionar</option>{(clients||[]).map((x:any)=><option key={x.id} value={x.id}>{x.nombre_completo}</option>)}</select></label><label><span className="label">Empleado</span><select className="field" value={form.empleado_id} onChange={e=>setForm({...form,empleado_id:e.target.value})} required><option value="">Seleccionar</option>{(employees||[]).map((x:any)=><option key={x.id} value={x.id}>{x.nombre_completo}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label><span className="label">Fecha</span><input className="field" type="date" value={form.fecha} onChange={e=>setForm({...form,fecha:e.target.value})} required/></label><label><span className="label">Hora</span><input className="field" type="time" value={form.hora_inicio} onChange={e=>setForm({...form,hora_inicio:e.target.value})} required/></label></div><div><span className="label">Servicios</span><div className="grid max-h-44 gap-2 overflow-auto rounded-xl border p-3">{(services||[]).map((s:any)=><label className="flex items-center gap-2" key={s.id}><input type="checkbox" checked={form.servicio_ids.includes(s.id)} onChange={()=>toggleService(s.id)}/><span>{s.nombre} · S/ {Number(s.precio).toFixed(2)} · {s.duracion_minutos} min</span></label>)}</div></div><label><span className="label">Notas</span><textarea className="field" value={form.notas} onChange={e=>setForm({...form,notas:e.target.value})}/></label><div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn-primary" disabled={save.isPending}>{editing?'Guardar cambios':'Crear cita'}</button></div></form></Modal>
  <Modal open={!!detail} title="Detalle de cita" onClose={()=>setDetail(null)}>{detail&&<div className="space-y-3"><p><b>Cliente:</b> {detail.cliente_nombre}</p><p><b>Empleado:</b> {detail.empleado_nombre}</p><p><b>Horario:</b> {detail.fecha} de {String(detail.hora_inicio).slice(0,5)} a {String(detail.hora_fin).slice(0,5)}</p><p><b>Servicios:</b> {detail.servicios.map((s:any)=>s.nombre).join(', ')}</p><p><b>Notas:</b> {detail.notas||'Sin notas'}</p><StatusBadge value={detail.estado}/></div>}</Modal>
 </div>
}
