import{useEffect,useMemo,useState}from'react';
import{useMutation,useQuery,useQueryClient}from'@tanstack/react-query';
import{useSearchParams}from'react-router-dom';
import{http,errorMessage}from'../api/http';import toast from'react-hot-toast';
import{Modal}from'../components/Modal';import{StatusBadge}from'../components/StatusBadge';
import{localToday}from'../utils/date';
import{CalendarClock,Pencil,XCircle,Check,Clock,Search,Sparkles,UserRound}from'lucide-react';
const today=localToday;const empty={empleado_id:'',fecha:today(),hora_inicio:'',servicio_ids:[] as string[],notas:''};
export function ClientAppointmentsPage({booking=false}:{booking?:boolean}){
 const [params]=useSearchParams();const preselected=params.get('servicio');
 const qc=useQueryClient();const[open,setOpen]=useState(booking||!!preselected);const[cancel,setCancel]=useState<any>(null);const[editing,setEditing]=useState<any>(null);const[f,setF]=useState<any>({...empty,servicio_ids:preselected?[preselected]:[]});const[serviceSearch,setServiceSearch]=useState('');const[category,setCategory]=useState('TODOS');const[tab,setTab]=useState<'proximas'|'historial'|'canceladas'>('proximas');
 const{data}=useQuery({queryKey:['my-client-appointments'],queryFn:async()=>{const r=await http.get('/client-portal/appointments',{params:{pagina:1,tamano_pagina:100}});return r.data}});
 const{data:services=[]}=useQuery({queryKey:['client-services'],queryFn:async()=>(await http.get('/client-portal/catalog/services')).data.data});
 const{data:employees=[]}=useQuery({queryKey:['client-employees',f.servicio_ids],enabled:f.servicio_ids.length>0,queryFn:async()=>(await http.get('/client-portal/catalog/employees',{params:{servicio_ids:f.servicio_ids},paramsSerializer:{indexes:null}})).data.data});
 const{data:slots=[]}=useQuery({queryKey:['client-slots',f.empleado_id,f.fecha,f.servicio_ids,editing?.id],enabled:!!f.empleado_id&&!!f.fecha&&f.servicio_ids.length>0,queryFn:async()=>(await http.get('/client-portal/catalog/available-slots',{params:{empleado_id:f.empleado_id,fecha:f.fecha,servicio_ids:f.servicio_ids,cita_id:editing?.id},paramsSerializer:{indexes:null}})).data.data});
 useEffect(()=>{if(f.empleado_id&&!employees.some((x:any)=>x.id===f.empleado_id))setF((v:any)=>({...v,empleado_id:'',hora_inicio:''}))},[employees]);
 useEffect(()=>{if(preselected&&services.some((s:any)=>s.id===preselected))setF((v:any)=>({...v,servicio_ids:[preselected]}))},[preselected,services]);
 const categories=useMemo(()=>['TODOS',...Array.from(new Set(services.map((s:any)=>s.categoria_nombre).filter(Boolean)))],[services]);
 const visibleServices=useMemo(()=>services.filter((s:any)=>{const q=serviceSearch.toLowerCase();return(category==='TODOS'||s.categoria_nombre===category)&&(!q||`${s.nombre} ${s.descripcion||''}`.toLowerCase().includes(q))}),[services,category,serviceSearch]);
 const selected=services.filter((s:any)=>f.servicio_ids.includes(s.id));const total=selected.reduce((a:number,s:any)=>a+Number(s.precio),0);const minutes=selected.reduce((a:number,s:any)=>a+Number(s.duracion_minutos),0);
 const refresh=()=>qc.invalidateQueries({queryKey:['my-client-appointments']});
 const save=useMutation({mutationFn:()=>editing?http.put(`/client-portal/appointments/${editing.id}`,f):http.post('/client-portal/appointments',f),onSuccess:()=>{toast.success(editing?'Cita reprogramada':'Cita reservada');setOpen(false);setEditing(null);setF(empty);refresh()},onError:e=>toast.error(errorMessage(e))});
 const cancelMut=useMutation({mutationFn:(x:any)=>http.patch(`/client-portal/appointments/${x.id}/cancel`,{motivo:x.motivo}),onSuccess:()=>{toast.success('Cita cancelada');setCancel(null);refresh()},onError:e=>toast.error(errorMessage(e))});
 const toggle=(id:string)=>setF((v:any)=>({...v,servicio_ids:v.servicio_ids.includes(id)?v.servicio_ids.filter((x:string)=>x!==id):[...v.servicio_ids,id],empleado_id:'',hora_inicio:''}));
 const edit=(x:any)=>{setEditing(x);setF({empleado_id:x.empleado_id,fecha:x.fecha,hora_inicio:String(x.hora_inicio).slice(0,5),servicio_ids:x.servicios.map((s:any)=>s.servicio_id),notas:x.notas||''});setOpen(true)};
 const items=(data?.items||[]) as any[];
 const filtered=items.filter(x=>tab==='canceladas'?['CANCELADA','NO_ASISTIO'].includes(x.estado):tab==='historial'?x.estado==='FINALIZADA':['PENDIENTE','CONFIRMADA','EN_PROCESO'].includes(x.estado));
 return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="page-title">Mis citas</h1><p className="text-slate-500">Gestiona tus reservas de manera simple y segura.</p></div><button className="btn-primary" onClick={()=>{setEditing(null);setF(empty);setOpen(true)}}><Sparkles size={17}/>Nueva cita</button></div>
 <div className="flex gap-2 overflow-auto">{([['proximas','Próximas'],['historial','Historial'],['canceladas','Canceladas']] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`whitespace-nowrap rounded-full px-4 py-1.5 text-sm font-bold ${tab===k?'bg-violet-600 text-white':'bg-slate-100 dark:bg-slate-800'}`}>{l}</button>)}</div>
 <div className="grid gap-3">{filtered.length===0?<div className="card py-12 text-center text-slate-500">{tab==='proximas'?'No tienes citas próximas.':tab==='historial'?'Todavía no tienes citas finalizadas.':'No tienes citas canceladas o no asistidas.'}</div>:filtered.map((x:any)=><div className="card" key={x.id}><div className="flex flex-wrap justify-between gap-3"><div><b>{x.fecha} · {String(x.hora_inicio).slice(0,5)}–{String(x.hora_fin).slice(0,5)}</b><p className="mt-1 flex items-center gap-1 text-sm"><UserRound size={15}/>{x.empleado_nombre}</p><p className="mt-1 text-sm text-slate-500">{x.servicios?.map((s:any)=>s.nombre).join(', ')}</p></div><div className="text-right"><StatusBadge value={x.estado}/><p className="mt-2 font-black text-violet-700">S/ {Number(x.precio_total).toFixed(2)}</p></div></div>{['PENDIENTE','CONFIRMADA'].includes(x.estado)&&<div className="mt-3 flex gap-2 border-t pt-3"><button className="btn-secondary !px-3 !py-2" onClick={()=>edit(x)}><Pencil size={16}/>Reprogramar</button><button className="btn-secondary !px-3 !py-2 text-rose-600" onClick={()=>setCancel({...x,motivo:''})}><XCircle size={16}/>Cancelar</button></div>}</div>)}</div>
 <Modal open={open} title={editing?'Reprogramar cita':'Reserva tu experiencia'} onClose={()=>setOpen(false)}><form className="grid gap-5" onSubmit={e=>{e.preventDefault();save.mutate()}}>
  <section><div className="mb-3 flex items-center justify-between"><span className="label !mb-0">1. Elige tus servicios</span><span className="text-xs font-bold text-violet-700">{f.servicio_ids.length} seleccionados</span></div><div className="relative mb-3"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="field pl-9" placeholder="Buscar servicio" value={serviceSearch} onChange={e=>setServiceSearch(e.target.value)}/></div><div className="mb-3 flex gap-2 overflow-auto">{categories.map((c:any)=><button type="button" key={c} onClick={()=>setCategory(c)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-xs font-bold ${category===c?'bg-violet-600 text-white':'bg-slate-100 dark:bg-slate-800'}`}>{c==='TODOS'?'Todos':c}</button>)}</div><div className="grid max-h-72 gap-3 overflow-auto pr-1 sm:grid-cols-2">{visibleServices.map((s:any)=>{const active=f.servicio_ids.includes(s.id);return <button type="button" onClick={()=>toggle(s.id)} key={s.id} className={`overflow-hidden rounded-2xl border text-left transition ${active?'border-violet-600 ring-2 ring-violet-200':'border-slate-200 hover:border-violet-300 dark:border-slate-700'}`}><div className="relative h-24"><img src={s.imagen_url||'/images/services/category-1.svg'} className="h-full w-full object-cover" alt=""/>{active&&<span className="absolute right-2 top-2 rounded-full bg-violet-600 p-1 text-white"><Check size={15}/></span>}</div><div className="p-3"><p className="font-black">{s.nombre}</p><div className="mt-1 flex items-center justify-between text-xs text-slate-500"><span><Clock size={13} className="inline"/> {s.duracion_minutos} min</span><b className="text-violet-700">S/ {Number(s.precio).toFixed(2)}</b></div></div></button>})}</div></section>
  {selected.length>0&&<div className="rounded-2xl bg-violet-50 p-4 dark:bg-violet-950/30"><div className="flex justify-between"><span className="font-bold">Resumen</span><span className="font-black text-violet-700">S/ {total.toFixed(2)}</span></div><p className="mt-1 text-sm text-slate-500">Duración estimada: {minutes} minutos</p></div>}
  <label><span className="label">2. Profesional disponible</span><select className="field" value={f.empleado_id} onChange={e=>setF({...f,empleado_id:e.target.value,hora_inicio:''})} required disabled={!f.servicio_ids.length}><option value="">Seleccionar profesional</option>{employees.map((x:any)=><option value={x.id} key={x.id}>{x.nombre_completo}{x.especialidad?` · ${x.especialidad}`:''}</option>)}</select></label>
  <label><span className="label">3. Fecha</span><input className="field" type="date" min={today()} value={f.fecha} onChange={e=>setF({...f,fecha:e.target.value,hora_inicio:''})} required/></label>
  <div><span className="label">4. Hora disponible</span><div className="grid grid-cols-3 gap-2 sm:grid-cols-4">{slots.map((x:any)=><button type="button" key={x.hora_inicio} onClick={()=>setF({...f,hora_inicio:String(x.hora_inicio).slice(0,5)})} className={`rounded-xl border px-2 py-2.5 text-sm font-bold ${f.hora_inicio===String(x.hora_inicio).slice(0,5)?'border-violet-600 bg-violet-600 text-white':'hover:border-violet-400'}`}>{String(x.hora_inicio).slice(0,5)}</button>)}</div>{f.empleado_id&&slots.length===0&&<p className="mt-2 text-sm text-amber-600">No hay horarios disponibles para esa fecha.</p>}</div>
  <label><span className="label">Notas para el profesional</span><textarea className="field" rows={3} placeholder="Ej.: cabello sensible, ocasión especial, preferencia de estilo..." value={f.notas} onChange={e=>setF({...f,notas:e.target.value})}/></label>
  <button className="btn-primary" disabled={!f.hora_inicio||save.isPending}><CalendarClock size={17}/>{editing?'Guardar reprogramación':'Confirmar reserva'}</button>
 </form></Modal>
 <Modal open={!!cancel} title="Cancelar cita" onClose={()=>setCancel(null)}><textarea className="field" placeholder="Indica el motivo" value={cancel?.motivo||''} onChange={e=>setCancel({...cancel,motivo:e.target.value})}/><button className="btn-primary mt-3" disabled={!cancel?.motivo?.trim()} onClick={()=>cancelMut.mutate(cancel)}>Confirmar cancelación</button></Modal></div>
}
