import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, Boxes, Eye, PackageCheck, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import toast from 'react-hot-toast';
import { http, errorMessage } from '../api/http';
import { Modal } from '../components/Modal';
import { Pagination } from '../components/Pagination';
import { StatusBadge } from '../components/StatusBadge';
import { useAuth } from '../auth/AuthContext';
import type { Paginated, Product } from '../types';

type Category={id:string;nombre:string};
type Supplier={id:string;razon_social:string};
const blank:any={nombre:'',marca:'',descripcion:'',precio_compra:'',precio_venta:'',stock_minimo:5,stock_maximo:30,unidad_medida:'UNIDAD',categoria_id:'',proveedor_id:'',codigo_barras:'',fecha_vencimiento:''};
const money=(v:number|string)=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(Number(v||0));

export function ProductsPage(){
 const{user}=useAuth();const isAdmin=user?.rol==='ADMINISTRADOR';
 const[page,setPage]=useState(1),[q,setQ]=useState(''),[open,setOpen]=useState(false),[detail,setDetail]=useState<Product|null>(null),[editing,setEditing]=useState<string|null>(null),[form,setForm]=useState<any>(blank);
 const qc=useQueryClient(); const invalidate=()=>qc.invalidateQueries({queryKey:['products']});
 const{data,isLoading}=useQuery({queryKey:['products',page,q],queryFn:async()=>{const r=await http.get<Paginated<Product>>('/products',{params:{pagina:page,tamano_pagina:12,busqueda:q||undefined}});return r.data}});
 const{data:categories=[]}=useQuery({queryKey:['product-categories'],queryFn:async()=>{const r=await http.get('/product-categories');return r.data.data as Category[]}});
 const{data:suppliers=[]}=useQuery({queryKey:['suppliers'],queryFn:async()=>{const r=await http.get('/suppliers');return r.data.data as Supplier[]}});
 const save=useMutation({mutationFn:()=>{const payload={...form,precio_compra:Number(form.precio_compra),precio_venta:Number(form.precio_venta),stock:0,stock_minimo:Number(form.stock_minimo||0),stock_maximo:form.stock_maximo===''?null:Number(form.stock_maximo),proveedor_id:form.proveedor_id||null,fecha_vencimiento:form.fecha_vencimiento||null,codigo_barras:form.codigo_barras||null};return editing?http.patch(`/products/${editing}`,payload):http.post('/products',payload)},onSuccess:()=>{toast.success(editing?'Producto actualizado':'Producto creado');setOpen(false);setEditing(null);setForm(blank);invalidate()},onError:e=>toast.error(errorMessage(e))});
 const remove=useMutation({mutationFn:(id:string)=>http.delete(`/products/${id}`),onSuccess:()=>{toast.success('Producto eliminado o inactivado');invalidate()},onError:e=>toast.error(errorMessage(e))});
 const items=data?.items||[]; const stats=useMemo(()=>({total:data?.total||0,low:items.filter(x=>x.stock<=x.stock_minimo).length,value:items.reduce((a,x)=>a+Number(x.precio_compra)*x.stock,0)}),[data,items]);
 const edit=(x:any)=>{setEditing(x.id);setForm({...blank,...x});setOpen(true)};
 return <div className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="page-title">Inventario profesional</h1><p className="text-slate-500">Productos, costos, precios, stock y proveedores en una sola vista.</p></div><button className="btn-primary" onClick={()=>{setEditing(null);setForm(blank);setOpen(true)}}><Plus size={18}/>Nuevo producto</button></div>
  <div className="grid gap-3 md:grid-cols-3"><div className="card flex items-center gap-3"><Boxes className="text-violet-600"/><div><div className="text-2xl font-bold">{stats.total}</div><div className="text-sm text-slate-500">Productos registrados</div></div></div><div className="card flex items-center gap-3"><AlertTriangle className="text-amber-500"/><div><div className="text-2xl font-bold">{stats.low}</div><div className="text-sm text-slate-500">Stock bajo en esta página</div></div></div><div className="card flex items-center gap-3"><PackageCheck className="text-emerald-600"/><div><div className="text-2xl font-bold">{money(stats.value)}</div><div className="text-sm text-slate-500">Valor de inventario visible</div></div></div></div>
  <div className="card"><div className="relative max-w-xl"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input className="field pl-10" placeholder="Buscar por nombre, código o marca" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/></div></div>
  <div className="table-wrap"><table><thead><tr><th>Producto</th><th>Categoría / Proveedor</th><th>Precios</th><th>Stock</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{isLoading?<tr><td colSpan={6}>Cargando...</td></tr>:items.map((x:any)=><tr key={x.id}><td><div className="font-semibold">{x.nombre}</div><div className="text-xs text-slate-400">{x.codigo} · {x.marca||'Sin marca'}</div></td><td><div>{x.categoria_nombre||categories.find(c=>c.id===x.categoria_id)?.nombre||'—'}</div><div className="text-xs text-slate-400">{x.proveedor_nombre||suppliers.find(s=>s.id===x.proveedor_id)?.razon_social||'Sin proveedor'}</div></td><td><div>Venta: <b>{money(x.precio_venta)}</b></div><div className="text-xs text-slate-400">Costo: {money(x.precio_compra)}</div></td><td><div className={x.stock<=x.stock_minimo?'font-bold text-amber-600':'font-semibold'}>{x.stock} {x.unidad_medida?.toLowerCase()}</div><div className="text-xs text-slate-400">Mín. {x.stock_minimo}</div></td><td><StatusBadge value={x.estado}/></td><td><div className="flex gap-1"><button className="btn-secondary !p-2" onClick={()=>setDetail(x)}><Eye size={16}/></button><button className="btn-secondary !p-2" onClick={()=>edit(x)}><Pencil size={16}/></button>{isAdmin&&<button className="btn-secondary !p-2 text-rose-600" onClick={()=>confirm('¿Eliminar o inactivar este producto?')&&remove.mutate(x.id)}><Trash2 size={16}/></button>}</div></td></tr>)}</tbody></table></div>
  <Pagination page={page} total={data?.total_paginas||1} onChange={setPage}/>
  <Modal open={open} title={editing?'Editar producto':'Nuevo producto'} onClose={()=>setOpen(false)}><form className="grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();save.mutate()}}>
   <div className="sm:col-span-2 rounded-xl border border-violet-200 bg-violet-50 p-3 text-sm text-violet-800 dark:border-violet-900 dark:bg-violet-950/30 dark:text-violet-200">El producto se crea con stock 0. Registra la mercadería desde <b>Compras</b> para aumentar existencias y dejar el movimiento auditado.</div><label className="sm:col-span-2"><span className="label">Nombre comercial</span><input className="field" value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})} required/></label>
   <label><span className="label">Categoría</span><select className="field" value={form.categoria_id} onChange={e=>setForm({...form,categoria_id:e.target.value})} required><option value="">Seleccionar</option>{categories.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label>
   <label><span className="label">Proveedor</span><select className="field" value={form.proveedor_id||''} onChange={e=>setForm({...form,proveedor_id:e.target.value})}><option value="">Sin proveedor</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.razon_social}</option>)}</select></label>
   {([['marca','Marca','text'],['codigo_barras','Código de barras','text'],['precio_compra','Precio de compra referencial','number'],['precio_venta','Precio de venta','number'],['stock_minimo','Stock mínimo','number'],['stock_maximo','Stock máximo','number'],['fecha_vencimiento','Fecha de vencimiento','date']] as string[][]).map(([k,l,t])=><label key={k}><span className="label">{l}</span><input className="field" type={t} step={t==='number'?'0.01':undefined} value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}
   <label><span className="label">Unidad de medida</span><select className="field" value={form.unidad_medida} onChange={e=>setForm({...form,unidad_medida:e.target.value})}><option>UNIDAD</option><option>BOTELLA</option><option>CAJA</option><option>PAQUETE</option><option>LITRO</option></select></label>
   <label className="sm:col-span-2"><span className="label">Descripción profesional</span><textarea className="field min-h-24" value={form.descripcion||''} onChange={e=>setForm({...form,descripcion:e.target.value})}/></label>
   <div className="sm:col-span-2 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn-primary" disabled={save.isPending}>Guardar producto</button></div>
  </form></Modal>
  <Modal open={!!detail} title="Ficha del producto" onClose={()=>setDetail(null)}>{detail&&<div className="grid gap-3 sm:grid-cols-2">{Object.entries({Producto:detail.nombre,Código:detail.codigo,Marca:detail.marca,Categoría:(detail as any).categoria_nombre,Proveedor:(detail as any).proveedor_nombre,'Precio venta':money(detail.precio_venta),'Precio compra':money(detail.precio_compra),Stock:`${detail.stock} ${detail.unidad_medida}`,Mínimo:detail.stock_minimo,Descripción:detail.descripcion,Estado:detail.estado}).map(([k,v])=><div key={k} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><div className="text-xs font-semibold uppercase text-slate-400">{k}</div><div>{v||'—'}</div></div>)}</div>}</Modal>
 </div>
}
