import{useMemo,useState}from'react';import{useMutation,useQuery,useQueryClient}from'@tanstack/react-query';import{http,errorMessage}from'../api/http';import toast from'react-hot-toast';import{Plus,Trash2,Eye,Truck}from'lucide-react';import{Modal}from'../components/Modal';import{Pagination}from'../components/Pagination';import{StatusBadge}from'../components/StatusBadge';
const money=(v:any)=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(Number(v||0));
type Line={producto_id:string;nombre:string;cantidad:number;costo_unitario:number;descuento:number};
export function PurchasesPage(){
 const qc=useQueryClient();const[page,setPage]=useState(1);const[open,setOpen]=useState(false);const[detail,setDetail]=useState<any>(null);
 const[proveedorId,setProveedorId]=useState('');const[lines,setLines]=useState<Line[]>([]);const[productoSel,setProductoSel]=useState('');const[descuentoGlobal,setDescuentoGlobal]=useState(0);const[impuesto,setImpuesto]=useState(0);const[obs,setObs]=useState('');
 const{data,isLoading}=useQuery({queryKey:['purchases',page],queryFn:async()=>{const{data}=await http.get('/purchases',{params:{pagina:page,tamano_pagina:10}});return data}});
 const{data:suppliers=[]}=useQuery({queryKey:['purchase-suppliers'],queryFn:async()=>{const r=await http.get('/suppliers');return r.data.data}});
 const{data:products=[]}=useQuery({queryKey:['purchase-products'],queryFn:async()=>{const r=await http.get('/products',{params:{pagina:1,tamano_pagina:200}});return r.data.items}});
 const subtotal=useMemo(()=>lines.reduce((a,l)=>a+l.cantidad*l.costo_unitario-l.descuento,0),[lines]);
 const total=Math.max(0,subtotal-descuentoGlobal+impuesto);
 const addLine=()=>{const p=products.find((x:any)=>x.id===productoSel);if(!p)return;if(lines.some(l=>l.producto_id===p.id))return toast.error('Ese producto ya está en la lista');setLines(v=>[...v,{producto_id:p.id,nombre:p.nombre,cantidad:1,costo_unitario:Number(p.precio_compra)||0,descuento:0}]);setProductoSel('')};
 const updateLine=(id:string,patch:Partial<Line>)=>setLines(v=>v.map(l=>l.producto_id===id?{...l,...patch}:l));
 const removeLine=(id:string)=>setLines(v=>v.filter(l=>l.producto_id!==id));
 const reset=()=>{setProveedorId('');setLines([]);setProductoSel('');setDescuentoGlobal(0);setImpuesto(0);setObs('')};
 const create=useMutation({mutationFn:()=>http.post('/purchases',{proveedor_id:proveedorId,descuento:descuentoGlobal,impuesto,observaciones:obs||null,
    detalles:lines.map(l=>({producto_id:l.producto_id,cantidad:l.cantidad,costo_unitario:l.costo_unitario,descuento:l.descuento}))}),
   onSuccess:()=>{toast.success('Compra registrada, stock actualizado');setOpen(false);reset();qc.invalidateQueries({queryKey:['purchases']});qc.invalidateQueries({queryKey:['products']})},
   onError:e=>toast.error(errorMessage(e))});
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(!proveedorId)return toast.error('Selecciona un proveedor');if(lines.length===0)return toast.error('Agrega al menos un producto');create.mutate()};
 const items=data?.items||[];
 return <div className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="page-title">Compras</h1><p className="text-slate-500">Entradas de mercadería y proveedores.</p></div><button className="btn-primary" onClick={()=>{reset();setOpen(true)}}><Plus size={18}/>Nueva compra</button></div>
  <div className="table-wrap"><table><thead><tr><th>Número</th><th>Proveedor</th><th>Fecha</th><th>Total</th><th>Estado</th><th/></tr></thead><tbody>{isLoading?<tr><td colSpan={6}>Cargando...</td></tr>:items.length===0?<tr><td colSpan={6} className="py-8 text-center text-slate-500">Todavía no hay compras registradas.</td></tr>:items.map((x:any)=><tr key={x.id}><td className="font-semibold">{x.numero_compra}</td><td>{x.proveedor_nombre||x.proveedor_id}</td><td>{new Date(x.fecha_compra||x.fecha||x.created_at).toLocaleDateString('es-PE')}</td><td>{money(x.total)}</td><td><StatusBadge value={x.estado}/></td><td><button className="btn-secondary !p-2" onClick={()=>setDetail(x)}><Eye size={16}/></button></td></tr>)}</tbody></table></div>
  <Pagination page={page} total={data?.total_paginas||1} onChange={setPage}/>
  <Modal open={open} title="Registrar compra" onClose={()=>setOpen(false)}><form className="grid gap-4" onSubmit={submit}>
   <label><span className="label">Proveedor</span><select className="field" value={proveedorId} onChange={e=>setProveedorId(e.target.value)} required><option value="">Seleccionar proveedor</option>{suppliers.map((s:any)=><option key={s.id} value={s.id}>{s.razon_social}</option>)}</select></label>
   <div><span className="label">Productos</span><div className="flex gap-2"><select className="field" value={productoSel} onChange={e=>setProductoSel(e.target.value)}><option value="">Seleccionar producto</option>{products.map((p:any)=><option key={p.id} value={p.id}>{p.nombre} (stock actual: {p.stock})</option>)}</select><button type="button" className="btn-secondary" onClick={addLine}><Plus size={16}/>Agregar</button></div></div>
   {lines.length>0&&<div className="table-wrap"><table><thead><tr><th>Producto</th><th>Cantidad</th><th>Costo unitario</th><th>Descuento</th><th>Subtotal</th><th/></tr></thead><tbody>{lines.map(l=><tr key={l.producto_id}><td className="font-semibold">{l.nombre}</td><td><input className="field !w-24" type="number" min="1" value={l.cantidad} onChange={e=>updateLine(l.producto_id,{cantidad:Math.max(1,Number(e.target.value))})}/></td><td><input className="field !w-28" type="number" min="0" step="0.01" value={l.costo_unitario} onChange={e=>updateLine(l.producto_id,{costo_unitario:Math.max(0,Number(e.target.value))})}/></td><td><input className="field !w-24" type="number" min="0" step="0.01" value={l.descuento} onChange={e=>updateLine(l.producto_id,{descuento:Math.max(0,Number(e.target.value))})}/></td><td className="font-semibold">{money(l.cantidad*l.costo_unitario-l.descuento)}</td><td><button type="button" className="text-rose-500" onClick={()=>removeLine(l.producto_id)}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>}
   <div className="grid gap-4 sm:grid-cols-2"><label><span className="label">Descuento global</span><input className="field" type="number" min="0" step="0.01" value={descuentoGlobal} onChange={e=>setDescuentoGlobal(Math.max(0,Number(e.target.value)))}/></label><label><span className="label">Impuesto</span><input className="field" type="number" min="0" step="0.01" value={impuesto} onChange={e=>setImpuesto(Math.max(0,Number(e.target.value)))}/></label></div>
   <label><span className="label">Observaciones (opcional)</span><textarea className="field" rows={2} value={obs} onChange={e=>setObs(e.target.value)}/></label>
   <div className="rounded-xl bg-violet-50 p-4 dark:bg-violet-950/30"><div className="flex justify-between text-sm"><span>Subtotal</span><span>{money(subtotal)}</span></div><div className="mt-1 flex justify-between text-lg font-black text-violet-700"><span>Total</span><span>{money(total)}</span></div></div>
   <div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn-primary" disabled={create.isPending}>{create.isPending?'Registrando...':'Registrar compra'}</button></div>
  </form></Modal>
  <Modal open={!!detail} title={detail?`Compra ${detail.numero_compra}`:''} onClose={()=>setDetail(null)}>{detail&&<div className="space-y-4"><div className="flex items-center gap-2 text-slate-500"><Truck size={18}/>{detail.proveedor_nombre}</div><div className="table-wrap"><table><thead><tr><th>Producto</th><th>Cantidad</th><th>Costo</th><th>Subtotal</th></tr></thead><tbody>{(detail.detalles||[]).map((d:any)=><tr key={d.producto_id}><td>{d.producto_nombre}</td><td>{d.cantidad}</td><td>{money(d.costo_unitario)}</td><td>{money(d.subtotal)}</td></tr>)}</tbody></table></div><div className="space-y-1 text-sm"><div className="flex justify-between"><span>Subtotal</span><b>{money(detail.subtotal)}</b></div><div className="flex justify-between"><span>Descuento</span><b>{money(detail.descuento)}</b></div><div className="flex justify-between"><span>Impuesto</span><b>{money(detail.impuesto)}</b></div><div className="flex justify-between text-lg font-black text-violet-700"><span>Total</span><span>{money(detail.total)}</span></div></div>{detail.observaciones&&<p className="rounded-lg bg-slate-50 p-2 text-sm text-slate-500 dark:bg-slate-900">Nota: {detail.observaciones}</p>}</div>}</Modal>
 </div>
}
